"""add last_attempt_at to webhook_deliveries

Revision ID: 1125b0055d59
Revises: 1172760b20de
Create Date: 2026-02-03 11:05:18.012400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1125b0055d59'
down_revision = '1172760b20de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_deliveries', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_deliveries', 'last_attempt_at')
    # ### end Alembic commands ###